"""Markdown formatter for PR review output."""

from typing import List
from .agent import ReviewResult, PRData


def format_review(pr_data: PRData, result: ReviewResult) -> str:
    """Format review result as structured Markdown.
    
    Args:
        pr_data: The PR data being reviewed
        result: The review result
        
    Returns:
        Formatted Markdown string
    """
    # Confidence emoji
    confidence_emoji = {
        "High": "🟢",
        "Medium": "🟡",
        "Low": "🔴"
    }.get(result.confidence, "⚪")
    
    # Build Markdown
    lines = [
        "## Summary",
        "",
        result.summary,
        "",
        "---",
        "",
        "## Identified Risks",
        "",
    ]
    
    # Add risks
    for risk in result.risks:
        lines.append(f"- ⚠️ {risk}")
    
    lines.extend([
        "",
        "---",
        "",
        "## Improvement Suggestions",
        "",
    ])
    
    # Add suggestions
    for suggestion in result.suggestions:
        lines.append(f"- 💡 {suggestion}")
    
    lines.extend([
        "",
        "---",
        "",
        "## Confidence Score",
        "",
        f"**{result.confidence}** {confidence_emoji}",
        "",
        "---",
        "",
        "## PR Details",
        "",
        f"- **Title**: {pr_data.title}",
        f"- **Author**: @{pr_data.author}",
        f"- **Repository**: {pr_data.repo}",
        f"- **Files Changed**: {pr_data.files_changed}",
        f"- **Additions**: +{pr_data.additions}",
        f"- **Deletions**: -{pr_data.deletions}",
        "",
        "---",
        "",
        "*Generated by Claude Review Agent*"
    ])
    
    return '\n'.join(lines)


def format_review_compact(pr_data: PRData, result: ReviewResult) -> str:
    """Format a compact review for GitHub comments.
    
    Args:
        pr_data: The PR data being reviewed
        result: The review result
        
    Returns:
        Compact Markdown string for GitHub comment
    """
    confidence_emoji = {
        "High": "🟢",
        "Medium": "🟡",
        "Low": "🔴"
    }.get(result.confidence, "⚪")
    
    lines = [
        "## 🤖 Claude Review Agent",
        "",
        f"**{result.confidence} Confidence** {confidence_emoji}",
        "",
        "### Summary",
        result.summary,
        "",
        "### Risks",
    ]
    
    for risk in result.risks:
        lines.append(f"- {risk}")
    
    lines.append("")
    lines.append("### Suggestions")
    
    for suggestion in result.suggestions:
        lines.append(f"- {suggestion}")
    
    lines.extend([
        "",
        "---",
        "*Reviewed by Claude Review Agent*"
    ])
    
    return '\n'.join(lines)
